services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  news_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod